// Курс построен как последовательное изучение грамматики ПО ТЕМАМ
// (без деления на уровни A1/A2/B1). Порядок — от опор к более сложному,
// чтобы не прыгать с темы на тему. Структура опирается на грамматику
// Тагиля и Die Gelbe. Предполагается, что человек уже не с нуля.
const MODULES = [
  {
    id: 'start',
    icon: '🔤',
    iconBg: '#ffd6e7',
    title: 'Старт: база',
    desc: 'Алфавит, чтение, приветствия, числа — если нужно освежить',
    lessons: [
      { id: 'alphabet',  title: 'Алфавит и произношение', desc: 'Умлауты ä/ö/ü/ß, ch, sch, ei/ie — правила чтения', xp: 30, type: 'Теория' },
      { id: 'greetings', title: 'Приветствия и прощания', desc: 'Hallo, Grüß Gott, Servus — в т.ч. австрийские', xp: 30, type: 'Диалоги' },
      { id: 'numbers',   title: 'Числа 1–100',            desc: 'Счёт, возраст, цены, телефоны', xp: 40, type: 'Практика' },
    ],
  },
  {
    id: 'nomen',
    icon: '📦',
    iconBg: '#ffc8df',
    title: 'Существительное и артикль',
    desc: 'Артикль, род, употребление артикля, множественное число, N-Deklination',
    lessons: [
      { id: 'articles-def',     title: 'Определённый артикль der, die, das', desc: 'Три рода + полное склонение по 4 падежам', xp: 50, type: 'Грамматика' },
      { id: 'articles-indef',   title: 'Неопределённый артикль ein, eine',   desc: 'ein/eine + склонение + отрицание kein/keine', xp: 45, type: 'Грамматика' },
      { id: 'artikel-gebrauch', title: 'Употребление артикля',               desc: 'Когда der, когда ein, когда без артикля', xp: 50, type: 'Грамматика' },
      { id: 'plural',           title: 'Множественное число',                desc: '5 основных типов образования', xp: 55, type: 'Грамматика' },
      { id: 'n-deklination',    title: 'N-Deklination (слабые сущ.)',        desc: 'der Student → den Studenten — -(e)n во всех падежах', xp: 55, type: 'Грамматика' },
    ],
  },
  {
    id: 'kasus',
    icon: '⚖️',
    iconBg: '#ffadd1',
    title: 'Падежи (склонение)',
    desc: 'Nominativ, Akkusativ, Dativ, Genitiv — кто кого кому чьего',
    lessons: [
      { id: 'nominativ', title: 'Именительный падеж (Nominativ)', desc: 'Кто? Что? — подлежащее, после sein/werden', xp: 45, type: 'Грамматика' },
      { id: 'akkusativ', title: 'Винительный падеж (Akkusativ)',  desc: 'Кого? Что? — прямой объект, предлоги, время', xp: 55, type: 'Грамматика' },
      { id: 'dativ',     title: 'Дательный падеж (Dativ)',        desc: 'Кому? Чему? — глаголы и предлоги Dativ', xp: 65, type: 'Грамматика' },
      { id: 'genitiv',   title: 'Родительный падеж (Genitiv)',    desc: 'Чьего? — принадлежность и предлоги', xp: 65, type: 'Грамматика' },
    ],
  },
  {
    id: 'pronomen',
    icon: '🙋',
    iconBg: '#ff99c8',
    title: 'Местоимения',
    desc: 'Личные (по падежам) и притяжательные',
    lessons: [
      { id: 'personal-pronouns', title: 'Личные местоимения',          desc: 'ich/mich/mir … — Nom/Akk/Dativ', xp: 45, type: 'Грамматика' },
      { id: 'possessivpron',     title: 'Притяжательные местоимения',  desc: 'mein/dein/sein/ihr по родам и падежам', xp: 55, type: 'Грамматика' },
    ],
  },
  {
    id: 'verb-praesens',
    icon: '🟢',
    iconBg: '#ffd6e7',
    title: 'Глагол: настоящее время',
    desc: 'sein/haben, правильные, сильные и смешанные глаголы в Präsens',
    lessons: [
      { id: 'verb-sein',       title: 'Глагол sein (быть)',              desc: 'ich bin, du bist … — и употребление', xp: 40, type: 'Грамматика' },
      { id: 'verb-haben',      title: 'Глагол haben (иметь)',            desc: 'ich habe, du hast … + Akkusativ, выражения', xp: 40, type: 'Грамматика' },
      { id: 'verb-heissen',    title: 'Меня зовут — heißen',             desc: 'Wie heißt du? Ich heiße …', xp: 35, type: 'Грамматика' },
      { id: 'praesens',        title: 'Präsens: правильные глаголы',     desc: 'machen, arbeiten, heißen — окончания и исключения', xp: 50, type: 'Грамматика' },
      { id: 'irregular-verbs', title: 'Сильные глаголы (e→i, a→ä)',      desc: 'sprechen, fahren, lesen — чередование гласных', xp: 55, type: 'Грамматика' },
      { id: 'mischverben',     title: 'Смешанные глаголы (Mischverben)', desc: 'denken→dachte, wissen, kennen', xp: 60, type: 'Грамматика' },
    ],
  },
  {
    id: 'verb-spezial',
    icon: '🔧',
    iconBg: '#ffb3d1',
    title: 'Глагол: модальные, отделяемые, возвратные',
    desc: 'können/müssen…, aufstehen…, sich freuen…',
    lessons: [
      { id: 'modal-verbs',     title: 'Модальные глаголы',         desc: 'können, müssen, wollen, dürfen — инфинитив в конец', xp: 60, type: 'Грамматика' },
      { id: 'trennbare-verben',title: 'Отделяемые глаголы',        desc: 'aufstehen, anrufen — приставка в конец', xp: 55, type: 'Грамматика' },
      { id: 'reflexive-verbs', title: 'Возвратные глаголы (sich)', desc: 'sich freuen, sich waschen — Akk и Dativ', xp: 60, type: 'Грамматика' },
    ],
  },
  {
    id: 'verb-zeit',
    icon: '⏪',
    iconBg: '#ffadd1',
    title: 'Прошедшее время и управление глаголов',
    desc: 'Perfekt, Präteritum, глаголы с предлогами',
    lessons: [
      { id: 'perfekt',              title: 'Прошедшее время Perfekt', desc: 'haben/sein + Partizip II', xp: 70, type: 'Грамматика' },
      { id: 'praeteritum',          title: 'Präteritum',              desc: 'war, hatte, ging — слабые и сильные', xp: 65, type: 'Грамматика' },
      { id: 'verben-praepositionen',title: 'Глаголы с предлогами',    desc: 'warten auf, denken an — управление', xp: 70, type: 'Грамматика' },
    ],
  },
  {
    id: 'adjektiv',
    icon: '✨',
    iconBg: '#ff99c8',
    title: 'Прилагательные',
    desc: 'Окончания после der/ein, степени сравнения',
    lessons: [
      { id: 'adjektiv-nach-def',  title: 'Прилагательные после der/die/das', desc: 'Слабое склонение: -e / -en', xp: 65, type: 'Грамматика' },
      { id: 'adjektiv-nach-indef',title: 'Прилагательные после ein/mein/kein',desc: 'Смешанное склонение: -er / -es', xp: 65, type: 'Грамматика' },
      { id: 'komparativ',         title: 'Komparativ и Superlativ',           desc: 'größer, am größten, als/wie, исключения', xp: 60, type: 'Грамматика' },
    ],
  },
  {
    id: 'praepositionen',
    icon: '📍',
    iconBg: '#ffd6e7',
    title: 'Предлоги',
    desc: 'Wechselpräpositionen: Wo? (Dativ) vs Wohin? (Akkusativ)',
    lessons: [
      { id: 'prepositions-place', title: 'Предлоги места и направления', desc: 'in/auf/an + Wo?/Wohin?, парные глаголы, zu/nach', xp: 60, type: 'Грамматика' },
    ],
  },
  {
    id: 'syntax',
    icon: '🧩',
    iconBg: '#ffb3d1',
    title: 'Синтаксис',
    desc: 'Порядок слов, отрицание, придаточные и относительные предложения',
    lessons: [
      { id: 'sentence-order',     title: 'Порядок слов (V2, инверсия, рамка)', desc: 'Глагол на 2-м месте, TeKaMoLo', xp: 50, type: 'Грамматика' },
      { id: 'negation',           title: 'Отрицание: nicht и kein',            desc: 'Что чем отрицаем + позиция nicht', xp: 45, type: 'Грамматика' },
      { id: 'subordinate-clauses',title: 'Придаточные предложения',            desc: 'weil, dass, wenn — глагол в конец', xp: 75, type: 'Грамматика' },
      { id: 'relativsatz',        title: 'Относительные предложения',          desc: 'der/die/das по роду и падежу', xp: 80, type: 'Грамматика' },
    ],
  },
  {
    id: 'advanced',
    icon: '🎓',
    iconBg: '#ff80b9',
    title: 'Продвинутое',
    desc: 'Konjunktiv II и пассивный залог',
    lessons: [
      { id: 'konjunktiv-2', title: 'Konjunktiv II (вежливость, условия)', desc: 'würde, wäre, hätte, könnte', xp: 80, type: 'Грамматика' },
      { id: 'passiv',       title: 'Пассивный залог (Passiv)',            desc: 'wird gemacht / wurde gemacht', xp: 80, type: 'Грамматика' },
    ],
  },
  {
    id: 'lexik',
    icon: '🇦🇹',
    iconBg: '#ffd6e7',
    title: 'Лексика и Австрия',
    desc: 'Страны и языки, лексика для поступления',
    lessons: [
      { id: 'countries', title: 'Страны и языки',                       desc: 'Deutschland, Österreich — откуда ты?', xp: 35, type: 'Лексика' },
      { id: 'b1-vocab',  title: 'Лексика: учёба и поступление в Австрии',desc: 'Bewerbung, Prüfung, Studium, Aufnahmetest', xp: 70, type: 'Лексика' },
    ],
  },
  {
    id: 'video-lessons',
    icon: '🎬',
    iconBg: '#ffe0b3',
    title: 'Видео-уроки (YouTube)',
    desc: 'Уроки по видео: Nicos Weg и курс @deutschmityehor',
    lessons: [
      { id: 'nicos-weg-1',   title: 'Привет, я Нико! — знакомство',     desc: 'Nicos Weg: sein, mein/meine, wer/was', xp: 40, type: 'Видео-урок' },
      { id: 'dmy-pronouns',  title: 'Личные местоимения',               desc: '@deutschmityehor: ich, du, er/sie/es, Sie/du/ihr', xp: 40, type: 'Видео-урок' },
      { id: 'dmy-verbs',     title: 'Спряжение правильных глаголов',     desc: '@deutschmityehor: machen, lernen, wohnen', xp: 45, type: 'Видео-урок' },
      { id: 'dmy-haben-sein',title: 'Глаголы haben и sein',             desc: '@deutschmityehor: иметь и быть', xp: 45, type: 'Видео-урок' },
      { id: 'dmy-modal',     title: 'Модальные глаголы',                 desc: '@deutschmityehor: können, wollen, müssen', xp: 50, type: 'Видео-урок' },
      { id: 'dmy-nouns',     title: 'Существительные и артикли',         desc: '@deutschmityehor: род, der/die/das', xp: 50, type: 'Видео-урок' },
    ],
  },
];
