const MODULES = [
  {
    id: 'a1-start',
    level: 'A1',
    icon: '🌱',
    iconBg: '#ffd6e7',
    title: 'Старт: основы языка',
    desc: 'Алфавит, произношение, приветствия, числа, местоимения',
    lessons: [
      { id: 'alphabet',         title: 'Алфавит и произношение',    desc: 'Умлауты ä/ö/ü/ß, ch, sch, ei/ie — правила чтения', xp: 30, type: 'Теория' },
      { id: 'greetings',        title: 'Приветствия и прощания',     desc: 'Hallo, Grüß Gott, Servus — в т.ч. австрийские', xp: 30, type: 'Диалоги' },
      { id: 'numbers',          title: 'Числа 1–100',                desc: 'Счёт, возраст, цены, телефоны', xp: 40, type: 'Практика' },
      { id: 'personal-pronouns',title: 'Личные местоимения',         desc: 'ich, du, er/sie/es, wir, ihr, sie/Sie', xp: 35, type: 'Грамматика' },
    ],
  },
  {
    id: 'a1-sein-haben',
    level: 'A1',
    icon: '👋',
    iconBg: '#ffc8df',
    title: 'Sein, haben, heißen — Die Gelbe Kap. 1',
    desc: 'Два главных глагола + знакомство. Основа всей немецкой грамматики',
    lessons: [
      { id: 'verb-sein',   title: 'Глагол sein (быть)',       desc: 'Ich bin, du bist, er ist — полное спряжение', xp: 40, type: 'Грамматика' },
      { id: 'verb-haben',  title: 'Глагол haben (иметь)',     desc: 'Ich habe, du hast — и устойчивые выражения', xp: 40, type: 'Грамматика' },
      { id: 'verb-heissen',title: 'Меня зовут — heißen',      desc: 'Wie heißt du? Ich heiße Margo.', xp: 35, type: 'Грамматика' },
      { id: 'countries',   title: 'Страны и языки',            desc: 'Deutschland, Österreich, Russland — откуда ты?', xp: 35, type: 'Лексика' },
    ],
  },
  {
    id: 'a1-nouns',
    level: 'A1',
    icon: '📚',
    iconBg: '#ffadd1',
    title: 'Артикли и существительные — Die Gelbe Kap. 2–3',
    desc: 'der/die/das, ein/eine, kein/keine, множественное число',
    lessons: [
      { id: 'articles-def',  title: 'Определённый артикль der, die, das', desc: 'Три рода + полное склонение по 4 падежам', xp: 50, type: 'Грамматика' },
      { id: 'articles-indef',title: 'Неопределённый артикль ein, eine',   desc: 'ein/eine + склонение + отрицание kein/keine', xp: 45, type: 'Грамматика' },
      { id: 'plural',        title: 'Множественное число',                 desc: '5 основных типов образования', xp: 55, type: 'Грамматика' },
      { id: 'n-deklination', title: 'N-Deklination (слабые сущ.)',         desc: 'der Student → den Studenten — -(e)n во всех падежах', xp: 55, type: 'Грамматика' },
    ],
  },
  {
    id: 'a1-verbs',
    level: 'A1',
    icon: '⚡',
    iconBg: '#ff99c8',
    title: 'Глаголы в Präsens — Die Gelbe Kap. 5–7',
    desc: 'Правильные, сильные, модальные и отделяемые глаголы',
    lessons: [
      { id: 'praesens',         title: 'Präsens: правильные глаголы',      desc: 'machen, lernen, wohnen — стандартное спряжение', xp: 50, type: 'Грамматика' },
      { id: 'irregular-verbs',  title: 'Сильные глаголы (e→i, a→ä)',       desc: 'sprechen, fahren, lesen — с чередованием гласных', xp: 55, type: 'Грамматика' },
      { id: 'modal-verbs',      title: 'Модальные: können, wollen, müssen', desc: 'Могу, хочу, должна — глагол в конец!', xp: 60, type: 'Грамматика' },
      { id: 'trennbare-verben', title: 'Отделяемые глаголы (Präfix)',       desc: 'aufstehen, anrufen, mitkommen — приставка в конец', xp: 55, type: 'Грамматика' },
    ],
  },
  {
    id: 'a1-cases',
    level: 'A1',
    icon: '🎯',
    iconBg: '#ffd6e7',
    title: 'Nominativ и Akkusativ — Die Gelbe Kap. 4',
    desc: 'Первые два падежа + отрицание + порядок слов V2',
    lessons: [
      { id: 'nominativ',     title: 'Именительный падеж (Nominativ)', desc: 'Кто? Что? — подлежащее', xp: 45, type: 'Грамматика' },
      { id: 'akkusativ',     title: 'Винительный падеж (Akkusativ)',  desc: 'Кого? Что? — меняется только мужской!', xp: 55, type: 'Грамматика' },
      { id: 'negation',      title: 'Отрицание: nicht и kein',        desc: 'Разница между nicht и kein раз и навсегда', xp: 45, type: 'Грамматика' },
      { id: 'sentence-order',title: 'Порядок слов — правило V2',      desc: 'Глагол всегда на 2-м месте!', xp: 50, type: 'Грамматика' },
    ],
  },
  {
    id: 'a2-cases',
    level: 'A2',
    icon: '🔵',
    iconBg: '#ffb3d1',
    title: 'Dativ и Genitiv — Die Gelbe Kap. 8–10',
    desc: 'Третий и четвёртый падежи + предлоги места и направления',
    lessons: [
      { id: 'dativ',             title: 'Дательный падеж (Dativ)',    desc: 'Кому? Чему? — меняются все роды', xp: 65, type: 'Грамматика' },
      { id: 'genitiv',           title: 'Родительный падеж (Genitiv)',desc: 'Чьего? — принадлежность и предлоги', xp: 65, type: 'Грамматика' },
      { id: 'prepositions-place',title: 'Предлоги места и направления',desc: 'in/auf/an/unter — wo? (Dativ) vs wohin? (Akkusativ)', xp: 60, type: 'Лексика + грамматика' },
    ],
  },
  {
    id: 'a2-adjektiv',
    level: 'A2',
    icon: '🎨',
    iconBg: '#ffd6e7',
    title: 'Прилагательные — Die Gelbe Kap. 11–13',
    desc: 'Окончания прилагательных, Komparativ, Superlativ',
    lessons: [
      { id: 'adjektiv-nach-def',  title: 'Прилагательные после der/die/das', desc: 'der alte Mann, die schöne Frau, das kleine Kind', xp: 65, type: 'Грамматика' },
      { id: 'adjektiv-nach-indef',title: 'Прилагательные после ein/eine',     desc: 'ein alter Mann, eine schöne Frau, ein kleines Kind', xp: 65, type: 'Грамматика' },
      { id: 'komparativ',         title: 'Komparativ и Superlativ',            desc: 'groß → größer → am größten. Исключения: gut, viel', xp: 60, type: 'Грамматика' },
    ],
  },
  {
    id: 'a2-past',
    level: 'A2',
    icon: '⏰',
    iconBg: '#ffadd1',
    title: 'Прошедшее время — Die Gelbe Kap. 14–16',
    desc: 'Perfekt (разговорное) и Präteritum (книжное)',
    lessons: [
      { id: 'perfekt',    title: 'Прошедшее время Perfekt',   desc: 'haben/sein + Partizip II — разговорное прошлое', xp: 70, type: 'Грамматика' },
      { id: 'praeteritum',title: 'Präteritum: sein и haben',  desc: 'war, hatte, wurde — книжное/нарративное прошлое', xp: 65, type: 'Грамматика' },
    ],
  },
  {
    id: 'a2-pronouns',
    level: 'A2',
    icon: '🔄',
    iconBg: '#ff99c8',
    title: 'Местоимения — Die Gelbe Kap. 17–18',
    desc: 'Возвратные глаголы, притяжательные местоимения в падежах',
    lessons: [
      { id: 'reflexive-verbs',title: 'Возвратные глаголы (sich)',     desc: 'sich waschen, sich freuen, sich interessieren für', xp: 60, type: 'Грамматика' },
      { id: 'possessivpron',  title: 'Притяжательные местоимения',    desc: 'mein/dein/sein/ihr в Nom./Akk./Dativ', xp: 55, type: 'Грамматика' },
    ],
  },
  {
    id: 'b1-sentences',
    level: 'B1',
    icon: '🚀',
    iconBg: '#ffb3d1',
    title: 'Сложные предложения — Die Gelbe Kap. 27–28',
    desc: 'Придаточные с weil/dass/wenn и относительные предложения',
    lessons: [
      { id: 'subordinate-clauses',title: 'Придаточные предложения',     desc: 'weil, dass, wenn, obwohl — глагол в конец!', xp: 75, type: 'Грамматика' },
      { id: 'relativsatz',        title: 'Относительные предложения',   desc: 'der/die/das меняется по падежу — сложный уровень', xp: 80, type: 'Грамматика' },
    ],
  },
  {
    id: 'b1-advanced',
    level: 'B1',
    icon: '🎓',
    iconBg: '#ff80b9',
    title: 'Konjunktiv II и Passiv — Die Gelbe Kap. 19–24',
    desc: 'Вежливость, условия, мечты и пассивный залог',
    lessons: [
      { id: 'konjunktiv-2',title: 'Konjunktiv II: вежливость и мечты', desc: 'würde, wäre, hätte, könnte — для общения в Австрии', xp: 80, type: 'Грамматика' },
      { id: 'passiv',      title: 'Пассивный залог (Passiv)',           desc: 'wird gemacht / wurde gemacht — как в официальных текстах', xp: 80, type: 'Грамматика' },
    ],
  },
  {
    id: 'b1-final',
    level: 'B1',
    icon: '🇦🇹',
    iconBg: '#ffd6e7',
    title: 'Финал: поступление в Австрии',
    desc: 'Лексика Bewerbung, официальный стиль, Österreich-Wissen',
    lessons: [
      { id: 'b1-vocab',title: 'Лексика: учёба и поступление в Австрии', desc: 'Bewerbung, Prüfung, Studium, Aufnahmetest — всё для вуза', xp: 70, type: 'Лексика' },
    ],
  },
  {
    id: 'video-lessons',
    level: 'A1',
    icon: '🎬',
    iconBg: '#ffe0b3',
    title: 'Видео-уроки (YouTube)',
    desc: 'Уроки по видео: Nicos Weg и курс @deutschmityehor',
    lessons: [
      { id: 'nicos-weg-1',   title: 'Привет, я Нико! — знакомство',     desc: 'Nicos Weg: sein, mein/meine, wer/was, первые фразы', xp: 40, type: 'Видео-урок' },
      { id: 'dmy-pronouns',  title: 'Личные местоимения',               desc: '@deutschmityehor: ich, du, er/sie/es, Sie/du/ihr', xp: 40, type: 'Видео-урок' },
      { id: 'dmy-verbs',     title: 'Спряжение правильных глаголов',     desc: '@deutschmityehor: machen, lernen, wohnen в Präsens', xp: 45, type: 'Видео-урок' },
      { id: 'dmy-haben-sein',title: 'Глаголы haben и sein',             desc: '@deutschmityehor: иметь и быть — полное спряжение', xp: 45, type: 'Видео-урок' },
      { id: 'dmy-modal',     title: 'Модальные глаголы',                 desc: '@deutschmityehor: können, wollen, müssen, dürfen', xp: 50, type: 'Видео-урок' },
      { id: 'dmy-nouns',     title: 'Существительные и артикли',         desc: '@deutschmityehor: род, der/die/das, множественное', xp: 50, type: 'Видео-урок' },
    ],
  },
];
