const MODULES = [
  {
    id: 'a1-basics',
    level: 'A1',
    icon: '🌱',
    iconBg: '#ffd6e7',
    title: 'Основы: первые шаги',
    desc: 'Алфавит, произношение, приветствия, числа, местоимения',
    lessons: [
      { id: 'alphabet', title: 'Алфавит и произношение', desc: 'Умлауты, ß и особые правила чтения', xp: 30, type: 'Теория + практика' },
      { id: 'greetings', title: 'Приветствия и прощания', desc: 'Hallo, Grüß Gott, Servus — в т.ч. австрийские', xp: 30, type: 'Диалоги' },
      { id: 'numbers', title: 'Числа 1–100', desc: 'Счёт, телефоны, возраст, цены', xp: 40, type: 'Практика' },
      { id: 'personal-pronouns', title: 'Личные местоимения', desc: 'ich, du, er/sie/es, wir, ihr, sie/Sie', xp: 35, type: 'Грамматика' },
    ],
  },
  {
    id: 'a1-intro',
    level: 'A1',
    icon: '👋',
    iconBg: '#ffc8df',
    title: 'Знакомство и рассказ о себе',
    desc: 'Sein, heißen, kommen aus — рассказываем о себе по-немецки',
    lessons: [
      { id: 'verb-sein', title: 'Глагол sein (быть)', desc: 'Ich bin, du bist, er ist — полное спряжение', xp: 40, type: 'Грамматика' },
      { id: 'verb-heissen', title: 'Меня зовут — heißen', desc: 'Wie heißt du? Ich heiße Margo.', xp: 35, type: 'Грамматика' },
      { id: 'countries', title: 'Страны и языки', desc: 'Deutschland, Österreich, Russland — откуда ты?', xp: 35, type: 'Лексика' },
    ],
  },
  {
    id: 'a1-nouns',
    level: 'A1',
    icon: '📚',
    iconBg: '#ffadd1',
    title: 'Существительные: der, die, das',
    desc: 'Артикли, род, множественное число — главная тема A1',
    lessons: [
      { id: 'articles-def', title: 'Определённый артикль der, die, das', desc: 'Три рода + подсказки по определению', xp: 50, type: 'Грамматика' },
      { id: 'articles-indef', title: 'Неопределённый артикль ein, eine', desc: 'ein/eine + отрицание kein/keine', xp: 45, type: 'Грамматика' },
      { id: 'plural', title: 'Множественное число', desc: '5 основных типов образования', xp: 55, type: 'Грамматика' },
    ],
  },
  {
    id: 'a1-verbs',
    level: 'A1',
    icon: '⚡',
    iconBg: '#ff99c8',
    title: 'Глаголы в настоящем времени',
    desc: 'Präsens, сильные глаголы, haben, модальные',
    lessons: [
      { id: 'praesens', title: 'Präsens: правильные глаголы', desc: 'machen, lernen, wohnen — стандартное спряжение', xp: 50, type: 'Грамматика' },
      { id: 'irregular-verbs', title: 'Сильные глаголы (e→i, a→ä)', desc: 'sprechen, fahren, lesen, essen — с чередованием', xp: 55, type: 'Грамматика' },
      { id: 'verb-haben', title: 'Глагол haben (иметь)', desc: 'Ich habe, du hast — и устойчивые выражения', xp: 45, type: 'Грамматика' },
      { id: 'modal-verbs', title: 'Модальные: können, wollen, müssen', desc: 'Могу, хочу, должна — глагол в конец!', xp: 60, type: 'Грамматика' },
    ],
  },
  {
    id: 'a1-cases',
    level: 'A1',
    icon: '🎯',
    iconBg: '#ffd6e7',
    title: 'Падежи A1: Nominativ и Akkusativ',
    desc: 'Первые два падежа + отрицание + порядок слов',
    lessons: [
      { id: 'nominativ', title: 'Именительный падеж (Nominativ)', desc: 'Кто? Что? — подлежащее', xp: 45, type: 'Грамматика' },
      { id: 'akkusativ', title: 'Винительный падеж (Akkusativ)', desc: 'Кого? Что? — меняется только мужской!', xp: 55, type: 'Грамматика' },
      { id: 'negation', title: 'Отрицание: nicht и kein', desc: 'Разница между nicht и kein раз и навсегда', xp: 45, type: 'Грамматика' },
      { id: 'sentence-order', title: 'Порядок слов — правило V2', desc: 'Глагол всегда на 2-м месте!', xp: 50, type: 'Грамматика' },
    ],
  },
  {
    id: 'a2-cases',
    level: 'A2',
    icon: '🚀',
    iconBg: '#ffb3d1',
    title: 'Уровень A2: Dativ, предлоги, Perfekt',
    desc: 'Третий падеж, предлоги места, прошедшее время',
    lessons: [
      { id: 'dativ', title: 'Дательный падеж (Dativ)', desc: 'Кому? Чему? — меняются все роды', xp: 65, type: 'Грамматика' },
      { id: 'prepositions-place', title: 'Предлоги места', desc: 'in, auf, an, unter, über — где? куда?', xp: 60, type: 'Лексика + грамматика' },
      { id: 'perfekt', title: 'Прошедшее время Perfekt', desc: 'haben/sein + Partizip II — разговорное прошлое', xp: 70, type: 'Грамматика' },
    ],
  },
  {
    id: 'b1-prep',
    level: 'B1',
    icon: '🎓',
    iconBg: '#ff80b9',
    title: 'Уровень B1: Финальный рывок',
    desc: 'Придаточные, Konjunktiv II, лексика для поступления',
    lessons: [
      { id: 'subordinate-clauses', title: 'Придаточные предложения', desc: 'weil, dass, wenn, obwohl — глагол в конец!', xp: 75, type: 'Грамматика' },
      { id: 'konjunktiv-2', title: 'Konjunktiv II: вежливость и мечты', desc: 'möchte, würde, könnte — для общения в Австрии', xp: 80, type: 'Грамматика' },
      { id: 'b1-vocab', title: 'Лексика: учёба и поступление в Австрии', desc: 'Bewerbung, Prüfung, Studium — всё для вуза', xp: 70, type: 'Лексика' },
    ],
  },
];
